{% set name = "ceffyl" %}
{% set version = "1.41.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ceffyl-{{ version }}.tar.gz
  sha256: 613f273225880f8075404a9cf9e608640c2dcb2f7344831e0cf3a4fb13bc2fe8

build:
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python
    - setuptools >=61.0
    - pip
  run:
    - python
    - encor >=1.1.5
    - enterprise-pulsar >=3.4.4,<4.0.0
    - enterprise_extensions >=3.0.2,<4.0.0
    - h5py >=3.11.0,<4.0.0
    - kalepy >=1.4,<2.0.0
    - kdepy >=1.1.0,<2.0.0
    - la_forge >=1.1.0,<2.0.0
    - natsort >=8.4.0,<9.0.0
    - numpy >=1.23.5,<3.0.0
    - ptmcmcsampler >=2.1.2,<3.0.0
  run_constrained:
    - holodeck-gw 1.*
    - kalepy 1.*

test:
  imports:
    - ceffyl

about:
  home: https://github.com/astrolamb/ceffyl/
  dev_url: https://github.com/astrolamb/ceffyl/
  summary: Software to rapidly and flexibly analyse Pulsar Timing Array data via the Generalised Factorised Likelihood (GFL)method
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - davecwright3
    - astrolamb
