{% set name = "ceffyl" %}
{% set version = "1.30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ceffyl-{{ version }}.tar.gz
  sha256: 305c7dd875af4448b861cc3055de6fab4603070d291412b93540a9103e1628d5

build:
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - wheel
    - numpy >=1.23.5,<2.0.0
    - cython >=0.29.33,<1.0.0
    - pip
  run:
    - python
    - encor >=1.1.2
    - enterprise_extensions >=2.4.2,<3.0.0
    - enterprise-pulsar >=3.3.2,<4.0.0
    - h5py >=3.7.0,<4.0.0
    - kdepy >=1.1.5,<2.0.0
    - la_forge >=1.0.2,<2.0.0
    - natsort >=8.2.0,<9.0.0
    - ptmcmcsampler >=2.1.1,<3.0.0
    - scipy >=1.10.0,<2.0.0
    - {{ pin_compatible('numpy') }}
  run_constrained:
    - holodeck-gw 1.*
    - kalepy 1.*

test:
  imports:
    - ceffyl

about:
  home: https://github.com/astrolamb/ceffyl/
  dev_url: https://github.com/astrolamb/ceffyl/
  summary: A software package to rapidly and flexibly analyse pulsar timing array (PTA) data via refiting to pulsar timing free spectra.\nThis can be done by fitting to a free spectrum of the entire PTA or to individual pulsars!
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - astrolamb
    - davecwright3
