{% set name = "ceffyl" %}
{% set version = "1.41" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ceffyl-{{ version }}.tar.gz
  sha256: 7c19aad47244f015314993832692f3494c4b268db380931776c890bd9d0137c6

build:
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - wheel
    - numpy >=1.23.5,<2.0.0
    - cython >=0.29.33,<1.0.0
    - pip
  run:
    - python
    - encor >=1.1.2
    - enterprise_extensions >=2.4.2,<3.0.0
    - enterprise-pulsar >=3.3.2,<4.0.0
    - h5py >=3.7.0,<4.0.0
    - kdepy >=1.1.5,<2.0.0
    - la_forge >=1.0.2,<2.0.0
    - natsort >=8.2.0,<9.0.0
    - ptmcmcsampler >=2.1.1,<3.0.0
    - scipy >=1.10.0,<2.0.0
    - {{ pin_compatible('numpy') }}
  run_constrained:
    - holodeck-gw 1.*
    - kalepy 1.*

test:
  imports:
    - ceffyl

about:
  home: https://github.com/astrolamb/ceffyl/
  dev_url: https://github.com/astrolamb/ceffyl/
  summary: Software to rapidly and flexibly analyse Pulsar Timing Array data via the Generalised Factorised Likelihood (GFL)method
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - davecwright3
    - astrolamb
